# ─────────────────────────────────────────────
# mosquitto.conf — Broker MQTT FDR Platform
# ─────────────────────────────────────────────

listener 1883
allow_anonymous false

# Fichiers d'authentification
password_file /mosquitto/config/passwd
acl_file      /mosquitto/config/acl

# Logs
log_type error
log_type warning
log_type notice
log_dest stdout

# Keepalive
max_keepalive 120
